export const actionsType = {
  // User
  FETCH_USER: 'FETCH_USER',
  FETCH_USER_FAIL: 'FETCH_USER_FAIL',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  CANCEL_FETCHING_USER: 'CANCEL_FETCHING_USER',
  // Loading
  SHOW_LOADING_ICON: 'SHOW_LOADING_ICON',
  HIDE_LOADING_ICON: 'HIDE_LOADING_ICON'
}
export const initState = {
  USERS: []
}
